### ISSUE TITLE
Homework Done

### ISSUE THREAD

**Issue by renestadler** [htl-perg-2019-20-5bhif/contact-list-exercise-renestadler#1]
Dear Mister Stropek!

I've succeeded with the current Contact-List-Exercise and want the extra point 😉.

Yours,
René Stadler

**Comment by rstropek** [comment]
...and you nearly earned it. You should not check the model manually. Use *data annotations* instead (e.g. [`[Required]`](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.requiredattribute?view=netcore-3.0). Fix that and the extra point will be yours.

Greetings,
Rainer Stropek

**Comment by renestadler** [comment]
Dear Mr. Stropek!
I have fixed now the issue mentioned above.
Yours, 
René Stadler
